In [3]:
import pandas as pd
import numpy as np

print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [4]:
import pandas as pd

df = pd.read_csv("Fraudulent_E-Commerce_Transaction_Data.csv")

In [5]:
df.head()

,Transaction ID,Customer ID,Transaction Amount,Transaction Date,Payment Method,Product Category,Quantity,Customer Age,Customer Location,Device Used,IP Address,Shipping Address,Billing Address,Is Fraudulent,Account Age Days,Transaction Hour
0,15d2e414-8735-46fc-9e02-80b472b2580f,d1b87f62-51b2-493b-ad6a-77e0fe13e785,58.09,2024-02-20 05:58:41,bank transfer,electronics,1.0,17.0,Amandaborough,tablet,212.195.49.198,Unit 8934 Box 0058\nDPO AA 05437,Unit 8934 Box 0058\nDPO AA 05437,0.0,30.0,5.0
1,0bfee1a0-6d5e-40da-a446-d04e73b1b177,37de64d5-e901-4a56-9ea0-af0c24c069cf,389.96,2024-02-25 08:09:45,debit card,electronics,2.0,40.0,East Timothy,desktop,208.106.249.121,"634 May Keys\nPort Cherylview, NV 75063","634 May Keys\nPort Cherylview, NV 75063",0.0,72.0,8.0
2,e588eef4-b754-468e-9d90-d0e0abfc1af0,1bac88d6-4b22-409a-a06b-425119c57225,134.19,2024-03-18 03:42:55,PayPal,home & garden,2.0,22.0,Davismouth,tablet,76.63.88.212,"16282 Dana Falls Suite 790\nRothhaven, IL 15564","16282 Dana Falls Suite 790\nRothhaven, IL 15564",0.0,63.0,3.0
3,4de46e52-60c3-49d9-be39-636681009789,2357c76e-9253-4ceb-b44e-ef4b71cb7d4d,226.17,2024-03-16 20:41:31,bank transfer,clothing,5.0,31.0,Lynnberg,desktop,207.208.171.73,"828 Strong Loaf Apt. 646\nNew Joshua, UT 84798","828 Strong Loaf Apt. 646\nNew Joshua, UT 84798",0.0,124.0,20.0
4,074a76de-fe2d-443e-a00c-f044cdb68e21,45071bc5-9588-43ea-8093-023caec8ea1c,121.53,2024-01-15 05:08:17,bank transfer,clothing,2.0,51.0,South Nicole,tablet,190.172.14.169,"29799 Jason Hills Apt. 439\nWest Richardtown, ...","29799 Jason Hills Apt. 439\nWest Richardtown, ...",0.0,158.0,5.0

In [6]:
df.shape

(70767, 16)

In [7]:
df.columns

Index(['Transaction ID', 'Customer ID', 'Transaction Amount',
       'Transaction Date', 'Payment Method', 'Product Category', 'Quantity',
       'Customer Age', 'Customer Location', 'Device Used', 'IP Address',
       'Shipping Address', 'Billing Address', 'Is Fraudulent',
       'Account Age Days', 'Transaction Hour'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70767 entries, 0 to 70766
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction ID      70767 non-null  object
 1   Customer ID         70767 non-null  object
 2   Transaction Amount  70766 non-null  float64
 3   Transaction Date    70766 non-null  object
 4   Payment Method      70766 non-null  object
 5   Product Category    70766 non-null  object
 6   Quantity            70766 non-null  float64
 7   Customer Age        70766 non-null  float64
 8   Customer Location   70766 non-null  object
 9   Device Used         70766 non-null  object
 10  IP Address          70766 non-null  object
 11  Shipping Address    70766 non-null  object
 12  Billing Address     70766 non-null  object
 13  Is Fraudulent       70766 non-null  float64
 14  Account Age Days    70766 non-null  float64
 15  Transaction Hour    70766 non-null  float64
dtypes: float64(6), object(10)
memory usage: 8.6+ MB

In [9]:
df.describe()

,Transaction Amount,Quantity,Customer Age,Is Fraudulent,Account Age Days,Transaction Hour
count,70766.000000,70766.000000,70766.000000,70766.000000,70766.000000,70766.000000
mean,226.113791,2.996057,34.489910,0.049374,179.459981,11.285674
std,263.868322,1.414053,10.007467,0.216649,106.546450,6.968183
min,10.000000,1.000000,-6.000000,0.000000,1.000000,0.000000
25%,68.325000,2.000000,28.000000,0.000000,86.000000,5.000000
50%,152.210000,3.000000,34.000000,0.000000,180.000000,11.000000
75%,296.305000,4.000000,41.000000,0.000000,271.000000,17.000000
max,5888.450000,5.000000,80.000000,1.000000,365.000000,23.000000

In [10]:
df.shape

(70767, 16)

In [11]:
df.isnull().sum()

Transaction ID        0
Customer ID           0
Transaction Amount    1
Transaction Date      1
Payment Method        1
Product Category      1
Quantity              1
Customer Age          1
Customer Location     1
Device Used           1
IP Address            1
Shipping Address      1
Billing Address       1
Is Fraudulent         1
Account Age Days      1
Transaction Hour      1
dtype: int64

In [12]:
df[df.isnull().any(axis=1)]

,Transaction ID,Customer ID,Transaction Amount,Transaction Date,Payment Method,Product Category,Quantity,Customer Age,Customer Location,Device Used,IP Address,Shipping Address,Billing Address,Is Fraudulent,Account Age Days,Transaction Hour
70766,6a1331fd-6ae3-4e09-9def-39bb50f00af4,84923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df = df.dropna()

In [14]:
df.shape

(70766, 16)

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.dtypes

Transaction ID         object
Customer ID            object
Transaction Amount    float64
Transaction Date       object
Payment Method         object
Product Category       object
Quantity              float64
Customer Age          float64
Customer Location      object
Device Used            object
IP Address             object
Shipping Address       object
Billing Address        object
Is Fraudulent         float64
Account Age Days      float64
Transaction Hour      float64
dtype: object

In [19]:
df["Transaction Date"] = pd.to_datetime(df["Transaction Date"])

In [20]:
df.dtypes

Transaction ID                object
Customer ID                   object
Transaction Amount           float64
Transaction Date      datetime64[ns]
Payment Method                object
Product Category              object
Quantity                     float64
Customer Age                 float64
Customer Location             object
Device Used                   object
IP Address                    object
Shipping Address              object
Billing Address               object
Is Fraudulent                float64
Account Age Days             float64
Transaction Hour             float64
dtype: object

In [21]:
df.describe()

,Transaction Amount,Transaction Date,Quantity,Customer Age,Is Fraudulent,Account Age Days,Transaction Hour
count,70766.000000,70766,70766.000000,70766.000000,70766.000000,70766.000000,70766.000000
mean,226.113791,2024-02-16 21:30:25.928200192,2.996057,34.489910,0.049374,179.459981,11.285674
min,10.000000,2024-01-01 00:05:36,1.000000,-6.000000,0.000000,1.000000,0.000000
25%,68.325000,2024-01-24 19:22:55.249999872,2.000000,28.000000,0.000000,86.000000,5.000000
50%,152.210000,2024-02-16 23:33:18,3.000000,34.000000,0.000000,180.000000,11.000000
75%,296.305000,2024-03-11 03:24:34.750000128,4.000000,41.000000,0.000000,271.000000,17.000000
max,5888.450000,2024-04-03 08:09:07,5.000000,80.000000,1.000000,365.000000,23.000000
std,263.868322,NaN,1.414053,10.007467,0.216649,106.546450,6.968183

In [22]:
df["Payment Method"].unique()

array(['bank transfer', 'debit card', 'PayPal', 'credit card'],
      dtype=object)

In [23]:
df["Product Category"].unique()

array(['electronics', 'home & garden', 'clothing', 'toys & games',
       'health & beauty'], dtype=object)

In [24]:
df["Device Used"].unique()

array(['tablet', 'desktop', 'mobile'], dtype=object)

In [25]:
df["Is Fraudulent"].value_counts()

Is Fraudulent
0.0    67272
1.0     3494
Name: count, dtype: int64

In [26]:
df.to_csv("Fraud_Cleaned.csv", index=False)

In [27]:
df.isnull().sum()

Transaction ID        0
Customer ID           0
Transaction Amount    0
Transaction Date      0
Payment Method        0
Product Category      0
Quantity              0
Customer Age          0
Customer Location     0
Device Used           0
IP Address            0
Shipping Address      0
Billing Address       0
Is Fraudulent         0
Account Age Days      0
Transaction Hour      0
dtype: int64

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df["Is Fraudulent"].value_counts()

Is Fraudulent
0.0    67272
1.0     3494
Name: count, dtype: int64

In [30]:
df["Payment Method"].unique()

array(['bank transfer', 'debit card', 'PayPal', 'credit card'],
      dtype=object)